#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab


################################
# 
# 默认wifi系列（本机使用可以用files大法，文件是etc/config下wireless）
# 修改的文件为 /trunk/package/kernel/mac80211/files/lib/wifi
# set wireless.radio${devidx}=wifi-device
# set wireless.radio${devidx}.type=mac80211
# set wireless.radio${devidx}.channel=1   -------指定频道
# set wireless.radio${devidx}.hwmode=11g  -------指定11g模式
# set wireless.radio${devidx}.country=CN  -------指定国家
# set wireless.radio${devidx}.htmode=HT40 -------40MHz带宽（单改无效，还需要改上面iw phy "$dev" info | grep -q 'Capabilities:' && htmode=HT40）
# set wireless.radio${devidx}.legacy_rates=1
# set wireless.radio${devidx}.noscan=1    -------强制40MHz带宽（默认无，需要添加）
# ${dev_id}
# ${ht_capab}
# set wireless.radio${devidx}.disabled=0  --------改为0默认开无线
# 
# set wireless.default_radio${devidx}=wifi-iface
# set wireless.default_radio${devidx}.device=radio${devidx}
# set wireless.default_radio${devidx}.network=lan
# set wireless.default_radio${devidx}.mode=ap
# set wireless.default_radio${devidx}.ssid=IOU              ---------指定SSID
# set wireless.default_radio${devidx}.encryption=psk2+ccmp  ---------指定加密模式
# set wireless.default_radio${devidx}.key=13143344          ---------指定密码（默认无，需要添加）

uci set wireless.default_radio0.disassoc_low_ack=0

uci set wireless.@wifi-device[0].disabled=0  #改为0自动打开wifi
uci set wireless.@wifi-device[0].txpower=17
uci set wireless.@wifi-device[0].hwmode=11g
uci set wireless.@wifi-device[0].channel=1
uci set wireless.@wifi-device[0].country=CN
uci set wireless.@wifi-device[0].htmode=HT40
uci set wireless.@wifi-device[0].legacy_rates=1
uci set wireless.@wifi-device[0].noscan=1

uci set wireless.@wifi-iface[0].network=lan
uci set wireless.@wifi-iface[0].mode=ap
uci set wireless.@wifi-iface[0].ssid=000-test
uci set wireless.@wifi-iface[0].encryption=psk2+ccmp
uci set wireless.@wifi-iface[0].key=fanpengtao

uci set network.lan.ipaddr=192.168.68.6
uci commit

################################


################################
# 设置默认上网方式: 
# 如果仅是自用固件，可以在该文件exit 0 上方适当的位置加上加入下列命令，设置Wan网口，添加路由器pppoe拨号账户密码，装好即可上网
# uci set network.wan.proto='pppoe'
# uci set network.wan.username='宽带账号'
# uci set network.wan.password='宽带密码'
# uci set network.wan.ifname='eth3'   //我的wan接口是eth3，你要根据自己的路由器情况改
# uci set network.wan6.ifname='eth3'
# uci commit network   

# 想要修改管理ip地址和lan口配置，可以在该文件exit 0 上方适当的位置加上加上下列命令
# uci set network.lan.ipaddr='192.168.68.6'    //改成你想要默认的管理ip
# uci set network.lan.proto='static'          //wan口静态IP方式
# uci set network.lan.type='bridge'           //设置桥接
# uci set network.lan.ifname='eth0 eth1 eth2 eth4 eth5' //根据自己的路由器情况改Lan口 
# uci commit network
################################

################################
# 7）更改openwrt后台web登陆用户名方法
# 1.修改/etc/passwd
# 将root:x:0:0:root:/root:/bin/ash修改为username:x:0:0:root:/root:/bin/ash。
# 
# 2.修改/etc/shadow
# 将root:xxxxxx:0:0:99999:7:::修改为username:xxxxxx:0:0:99999:7:::。
# 
# 3.修改/usr/lib/lua/luci/controller/admin/index.lua
# 将page.sysauth = {“root”}修改为page.sysauth = {“username”}。
# 
# 4.修改/usr/lib/lua/luci/controller/admin/servicectl.lua
# 将entry({“servicectl”}, alias(“servicectl”, “status”)).sysauth = {“root”}修改为entry({“servicectl”}, alias(“servicectl”, “status”)).sysauth = {“username”}。
################################

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

ln -sf /sbin/ip /usr/bin/ip

# the tencent cloud do not work. for examlt GFW repo...
#sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf

sed -i 's/root::0:0:99999:7:::/root:$1$.UTM34XD$BRs6ch6HTyaKeJUlHhsQx0:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$.UTM34XD$BRs6ch6HTyaKeJUlHhsQx0:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

#echo 'iptables -A OUTPUT -m string --string "api.installer.xiaomi.cn" --algo bm --to 65535 -j DROP' >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='X86-64 R23.7.7'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Build @20230715 by 小祖宗 '" >> /etc/openwrt_release


sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# Enable ssh RootLogin
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
service sshd restart

# change the current theme to design.
# ! BE CAREFUL: must select he design theme at .config file first 
sed -i "s/\(option mediaurlbase '\/luci-static\/\).*'$/\1material'/" /etc/config/luci

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
